language: python
python:
  - "3.5"

install:
  - pip install -r requirements/dev.txt
  - pip install codecov

script:
  # - python -m unittest discover
  # - behave
  # - coverage erase
  # - coverage run test_webapp.py && coverage html
  - python test.py

after_success:
  - codecov
